# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, devel]


name: R-CMD-check

jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
  fetch-check-repo:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      TEST_NAME: "ffpe"
    steps:
      - name: create repo
        run: |
          echo $REPO_NAME
          git clone "https://git.bioconductor.org/packages/$TEST_NAME"
          rsync -a --exclude "^\\." $TEST_NAME/* .
          rm -rf $TEST_NAME
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, LiNk-NY/Rnw2Rmd
          needs: check
      - name: convert Rnw
        run: |
          R -e 'setwd("vignettes")
                 for (fname in list.files(path = ".", pattern = "\\.rnw$", ignore.case = TRUE)){
                  Rnw2Rmd::Rnw2Rmd(from = fname, to = sub("rnw", "Rmd", x = fname, ignore.case = TRUE), validate = FALSE)
                 }'
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    #  - uses: r-lib/actions/check-r-package@v2
